on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate Empty Requisite Files
      run: go generate
    - name: Build
      run: go build